/**
 * The console's view of the engine contract.
 *
 * These mirror `services/drift-engine/pkg/driftv1`. They are hand-written for
 * now and will be generated by `cmd/gencontracts` once the shape settles —
 * tracked in docs/BUILD-LOG.md rather than left as an unspoken TODO.
 */

export type ClaimTier = 'core' | 'standard' | 'peripheral'
export type ClaimStatus = 'active' | 'retired' | 'contested'
export type AssertionState = 'verified' | 'stale' | 'contradicted' | 'orphaned'

export type DriftKind =
  | 'added'
  | 'retired'
  | 'contradicted'
  | 'weakened'
  | 'citation_broken'
  | 'instruction_archived'

export type Detector = 'outline_presence' | 'typed_value' | 'citation_graph' | 'instruction_lifecycle' | 'semantic'

/**
 * What sort of published thing depends on a claim.
 *
 * Only `page` has a document to patch. Everything else is downstream of the
 * Knowledge Base and stops repeating the old value when the next build lands,
 * not when somebody approves a paragraph — which is why the queue and the gate
 * both branch on this rather than assuming every dependent is editable.
 */
export type SurfaceKind = 'page' | 'agent' | 'feed' | 'template'

export type WorkflowState = 'detected' | 'triage' | 'drafting' | 'review' | 'published' | 'dismissed'

export interface Source {
  id: string
  title: string
  kind: string
  uri: string
  owner: string
  authority: number
  changedAt: string
}

export interface Claim {
  id: string
  path: string
  statement: string
  value?: number
  unit?: string
  tier: ClaimTier
  citations: string[]
  status: ClaimStatus

  /**
   * Lineage. Three build IDs, stamped by the engine's ledger on every capture.
   *
   *   firstSeenBuild     where did this come from?      (created)
   *   lastVerifiedBuild  when was it last re-confirmed? (verified)
   *   lastChangedBuild   when did it last move?         (changed)
   *
   * `lastVerifiedBuild` deliberately does not advance on a build that altered
   * the claim, so the pair reads as "last confirmed at 46, moved at 47" — the
   * last moment the fact was boring, and the moment it stopped being.
   */
  firstSeenBuild?: string
  lastVerifiedBuild?: string
  lastChangedBuild?: string
}

/**
 * A published place that can depend on a claim.
 *
 * A content page is one. So is an agent answering from the Knowledge Base, a
 * syndicated feed, an email template. They differ in how you correct them and
 * not at all in how they go wrong.
 */
export interface Surface {
  id: string
  kind: SurfaceKind
  title: string
  owner: string
  locator?: string
}

export interface ContentPage {
  id: string
  title: string
  slug: string
  summary: string
  body: string[]
  owner: string
}

export interface Assertion {
  id: string
  claimId: string
  /** Set for page assertions. Exactly one of `pageId` and `surfaceId` is present. */
  pageId?: string
  /** Set for a non-page dependent: an agent, a feed, a template. */
  surfaceId?: string
  fieldPath: string
  /** Portable Text `_key` of the addressed block — stable under reordering. */
  blockKey?: string
  renderedText: string
  verifiedAgainstBuild: string
  state: AssertionState
}

export interface CompetingValue {
  statement: string
  value?: number
  unit?: string
  sourceId: string
  authority: number
}

export interface Conflict {
  path: string
  competingValues: CompetingValue[]
  resolvedBy?: string
}

export interface BuildSnapshot {
  id: string
  kbId: string
  buildNumber: number
  builtAt: string
  outlineHash: string
  claims: Claim[]
  conflicts: Conflict[] | null
  instructionsActive: string[] | null
  instructionsArchived: string[] | null
}

export interface DriftEvent {
  fromBuild: string
  toBuild: string
  claimPath: string
  claimId: string
  kind: DriftKind
  before?: string
  after?: string
  confidence: number
  detectedBy: Detector
  tier: ClaimTier
  blastRadius: string[]
  workflowState: WorkflowState
}

export interface Summary {
  totalEvents: number
  needingReview: number
  /** Every published place still expressing a changed claim — pages and agents. */
  affectedDependents: number
  unresolvedConflicts: number
}

/** Everything the console renders. */
export interface DriftData {
  builds: BuildSnapshot[]
  claims: Claim[]
  pages: ContentPage[]
  /** Every dependency — page assertions and surface dependencies alike. */
  assertions: Assertion[]
  surfaces: Surface[]
  sources: Source[]
  events: DriftEvent[]
  summary: Summary
}

/**
 * The seam between the console and its data.
 *
 * Two implementations: `fixtureSource` reads engine output committed to the
 * repo, and `sanitySource` (added once the org Labs flag clears) reads live
 * documents through App SDK hooks. Everything above this line is identical in
 * both cases, so the UI cannot quietly depend on fixture-only behaviour.
 */
export interface DriftDataSource {
  readonly kind: 'fixture' | 'sanity'
  load(): DriftData
}
